### PR TITLE
Use fsGroup from the Pod's securityContext to determine uid/gid for mount opts

### PR DESCRIPTION
**Pull request by juliohm1978**

### CODE REVIEW

**Comment by spawnia** [comment]
This is not working in Kubernetes versions below `v1.15` (i tried in `v1.14.8`).

I dug in and found that the input for `fsGroup` is different than you expected:

```json
{
  "kubernetes.io/fsGroup": "33",
  ...
}
```

The rest of the arguments is passed as expected.

Looks like that change was made in `v1.15`: https://github.com/kubernetes/kubernetes/commit/5b97b2860d9b490eba3325bb1e3ae0a748222d9d
Everything works fine there, nicely done!

How about we add in a fallback to look in both fields?

**Comment by juliohm1978** [comment]
New PR coming tonight.

**Comment by juliohm1978** [comment]
New commit coming later

**Comment by juliohm1978** [comment]
A new 0.5-beta was built on top of the existing. I'll run some tests here and let you know.

**Comment by juliohm1978** [comment]
Seems ok on v1.14.8 now. Will post a new release as soon as I get a feedback.

**Comment by spawnia** [comment]
It worked great.

Thank you for implementing this, it was great to peek into the inner workings a little bit. Interesting stuff.

**Pull request merged**
